function [fitresult, gof] = FitSurface(tmpx, tmpy, tmpz, PD)
%CREATEFIT(TMPX,TMPY,TMPZ)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : tmpx
%      Y Input : tmpy
%      Z Output: tmpz
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Oct-2018 16:51:51


%%

if nargin < 4
    PD = 0;
end

% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( tmpx, tmpy, tmpz );

% Set up fittype and options.
ft = fittype( 'poly22' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
if PD == 1
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'tmpz vs. tmpx, tmpy', 'Location', 'NorthEast' );
% Label axes
xlabel tmpx
ylabel tmpy
zlabel tmpz
grid on
view( -51.9, 51.6 );
end


